---

- name: Setup Logtail
  hosts: fullnode
  become: true
  tasks:

  - name: Download fluent-bit GPG key using get_url
    become: yes
    ansible.builtin.apt_key:
      url: https://packages.fluentbit.io/fluentbit.key
      state: present

  - name: Equivilent of apt-update
    apt:
      update_cache: yes

  - name: Add fluent-bit repository to sources list.
    apt_repository:
      # Ubuntu 20.04 is called Jammy - change this if needed. Focal will cause issues with install.
      repo: deb https://packages.fluentbit.io/ubuntu/jammy jammy main
      state: present
      filename: 'fluentbit'
      update_cache: yes

  - name: Install dependencies
    apt:
      pkg:
      - fluent-bit

    
  - name: Write fluent-bit config file
    template:
      src: fluent_bit_fullnode.conf
      dest: /etc/fluent-bit/fluent-bit.conf
      mode: 0644
      owner: sui
      group: sui
      
  - name: Refresh systemd
    command: systemctl daemon-reload

  - name: Enable fluent-bit.service
    systemd:
      name: fluent-bit.service
      enabled: yes

  - name: Start fluent-bit via systemd
    systemd:
      name: fluent-bit.service
      state: started