---

- name: Remove Sui core database files
  hosts: fullnode
  become: no
  remote_user: sui
  tasks:

  - name: Remove Sui core database files
    file:
      path: /opt/sui/sui-db-files/suidb
      state: absent
